name: Run Playwright Java Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install playwright dependencies
        run: |
          npm install
          npm install playwright

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb sudo

      - name: Add a user with sudo privileges
        run: |
          sudo useradd -m user
          sudo usermod -aG sudo user

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Start Local Application
        run: |
          docker-compose up -d

      - name: Wait for Application to Start
        run: sleep 60s

      - name: Run Playwright Java tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng.xml

      - name: Stop Local Application
        run: |
          docker-compose down
