name: Run Playwright Java Tests

on:
  push:
    branches:
      - main
      
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install playwright dependencies
        run: |
          npm install
          npm install playwright

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Local Application
        run: |
          docker-compose up -d

      - name: Wait for Application to Start
        run: sleep 60s

      - name: Run Playwright Java tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng.xml

      - name: Stop Local Application
        run: |
          docker-compose down
