name: Run Playwright Java Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install playwright dependencies
        run: |
          npm install
          npm install playwright

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb sudo

      - name: Add a user with sudo privileges
        run: |
          CONTAINER_ID=$(docker ps -q)
          docker exec -u 0 -it $CONTAINER_ID useradd -m user
          docker exec -u 0 -it $CONTAINER_ID usermod -aG sudo user

      - name: Build Docker Images
        run: |
          docker-compose build

      - name: Start Local Application
        run: |
          CONTAINER_ID=$(docker ps -q)
          docker exec -u user -it $CONTAINER_ID xvfb-run -a docker-compose up -d

      - name: Wait for Application to Start
        run: sleep 60s

      - name: Run Playwright Java tests
        run: |
          CONTAINER_ID=$(docker ps -q)
          docker exec -u user -it $CONTAINER_ID mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng.xml

      - name: Stop Local Application
        run: |
          docker-compose down

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
          
      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test Summary Report'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url:  https://github.com/abdulrahmanMohamed2020/parabank/${{ github.run_number }}
